'use strict';

const MIN_MULTIPART_SIZE = 4 << 20; // 4MB
const MAX_PUTOBJECT_SIZE = 5 << 30; // 5GB
const MAX_MULTIPART_COUNT = 10000;

exports.MIN_MULTIPART_SIZE = MIN_MULTIPART_SIZE;
exports.MAX_PUTOBJECT_SIZE = MAX_PUTOBJECT_SIZE;
exports.MAX_MULTIPART_COUNT = MAX_MULTIPART_COUNT;
