on:
  push:
    tags:
    - 'v*'
name: Build Release
jobs:
  create_release:
    name: Create release for new version
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release Notes
          draft: true
          prerelease: false
  release-linux-amd64:
    name: release for linux/amd64
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: test
        run: make i test
      - name: build
        run: make linux64
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/kodo-browser-linux-x64-${{ steps.vars.outputs.tag }}.zip
          asset_name: kodo-browser-linux-x64-${{ steps.vars.outputs.tag }}.zip
          asset_content_type: application/zip
  release-win-amd64:
    name: release for win/amd64
    runs-on: windows-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        shell: bash
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: test
        run: make i test
      - name: build
        run: make win64
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/kodo-browser-win32-x64-${{ steps.vars.outputs.tag }}.zip
          asset_name: kodo-browser-win32-x64-${{ steps.vars.outputs.tag }}.zip
          asset_content_type: application/zip
  release-darwin-amd64:
    name: release for darwin/amd64
    runs-on: macos-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: test
        run: make i test
      - name: build
        run: make mac
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build/kodo-browser-darwin-x64-${{ steps.vars.outputs.tag }}.zip
          asset_name: kodo-browser-darwin-x64-${{ steps.vars.outputs.tag }}.zip
          asset_content_type: application/zip
